### ISSUE TITLE
Error when attempting to compile

### ISSUE THREAD

**Issue by dvn0** [ba0f3/uibuilder.nim#1]
This is an exciting project! I know you just started, and it's a prototype, but I thought I'd report this anyway. When I run ```nim c uibuilder.nim``` It fails with this message:

```sh
uibuilder.nim(30, 30) Error: type mismatch: got <Builder, XmlNode>
but expected one of: 
proc build(builder: Builder; node: XmlNode; parent: var Widget)
  first type mismatch at position: 3
  required type: var Widget

expression: build(builder, child)
```

**Comment by ba0f3** [comment]
thank you for interesting, I will try to make it works soon

**Comment by dvn0** [comment]
awesome! it works for me now :)
