### ISSUE TITLE
Install fail with XML error

### ISSUE THREAD

**Issue by dvn0** [ba0f3/uibuilder.nim#3]
When I run "nimble install" it fails with:
`Error: Build failed for package: uibuilder`

**Further down are the details:**

`$HOME/.nimble/pkgs/xml-#devel/xml.nim(170, 24) Error: usage of 'isNil' is a user-defined error`

I'm using latest head of nim compiler (0.18.1) and recent nimble too.

**Comment by ba0f3** [comment]
thanks, I will fix `xml.nim` soon

**Comment by dvn0** [comment]
Thanks for the quick fix! Unfortunately it's still failing with the same error for me...

**Comment by ba0f3** [comment]
try to reinstall xml's devel version with `nimble install xml@#devel`

**Comment by dvn0** [comment]
I tried, and still the same issue... strange.

**Comment by ba0f3** [comment]
please try again, dont forget to pull latest commit of `uibuilder` too

**Comment by dvn0** [comment]
ok - still have the  ` ... uibuilder.nim(156, 24) Error: usage of 'isNil' is a user-defined error `

**EDIT:** Now I realize that this error message is somewhat different than the first one.

Not sure if this is relevant, or not: 
```
egrep -nr "isNil" uibuilder.nim
115:  if parent.isNil:
156:  if not root.children.isNil:
162:  if not root.children.isNil:
270:  if not root.children.isNil:
```

also have this new -presumably unrelated- warning
` ... uibuilder.nim(141, 18) Warning: only GtkMenuItem and GtkCheckMenuItem is supported [User]`

**Comment by ba0f3** [comment]
did you run it from source? so, you need latest commit of `uibuilder`. else I will make a new release for it

**Comment by dvn0** [comment]
Yes, I am running from source with the latest commit. Master branch.

**Comment by ba0f3** [comment]
strange, did you pull this commit?  https://github.com/ba0f3/uibuilder.nim/commit/efe319b428dd396989f895bd2afe56f700d0e395

**Comment by dvn0** [comment]
Yes, that's the latest commit I have.

Just to be clear on what I'm doing:

In the root of the git repo, I run `nimble install`

**Comment by ba0f3** [comment]
try `nimble test` first

**Comment by ba0f3** [comment]
alright I see it, `nimble test` works but `nimble install` got error. I will fix it soon

**Comment by ba0f3** [comment]
fixed, just pull the latest commit, thanks!

**Comment by dvn0** [comment]
Now I have different errors. It might just be specific to me, I'm not sure. You can take a look here:

https://paste.debian.net/hidden/f9c65f86/

**Comment by ba0f3** [comment]
this is an known error. just recompile with `-f` switch, or remove cache folder `rm -rf /home/person/.cache/nim/uibuilder_r` and try again
