### ISSUE TITLE
Err: "cannot evaluate at compile time: state"

### ISSUE THREAD

**Issue by ThomasTJdev** [ba0f3/uibuilder.nim#5]
Hi @ba0f3 

I just got an issue on the nimblegui due to an error while compiling. Are you going for an update of uibuilder anytime soon?

```
/nim/nim_nimble_gui/nimblegui.nim(7, 6) template/generic instantiation of `build` from here
/.choosenim/toolchains/nim-1.0.4/lib/pure/random.nim(593, 3) Error: cannot evaluate at compile time: state
```

**Comment by ba0f3** [comment]
Pegs stopped working in compile time https://github.com/nim-lang/Nim/issues/9009, I will try to make a workaround when I have spare time.

Thank you and Happy New Year!

**Comment by ThomasTJdev** [comment]
Super :) !

Happy New Year to you too :tada:

**Comment by ThomasTJdev** [comment]
Hi @ba0f3 

I hope you had a great New Year :wink: - any plans for this?

**Comment by ba0f3** [comment]
Oh gosh, I'm sorry I forgot about this. I will take a look tonight

**Comment by ThomasTJdev** [comment]
Hi @ba0f3 

Just to let you know, I have just accepted a PR for nimble_gui, which implementes `webgui` instead of `uibuilder`...

**Comment by ba0f3** [comment]
glad that you found a way to moving forward. Im sorry but libui is a big dead elephant therefor fixing its related projects is my lowest priority.
